### ISSUE TITLE
Reading files from VMFS is buggy

### ISSUE THREAD

**Issue by szolnokit** [glandium/vmfs-tools#25]
I tried copy files from a big (~4TB) VMFS6 datastore to an Ext4 formatted HDD but reading files with vmfs6-tools very buggy.

Steps:
1. Stop all VM-s completly in my ESXi homelab server. 
2. Make md5 list in every VM folder from every files, in ESXi SSH shell (md5sum command).
3. Shut down ESXi cleanly. 

2. Put a destination HDD in my server, and boot Debian 10 Live
3. Set source VMFS HDD as read only (just for safe), and mount the VMFS with vmfs6-fuse as read only.
4. Mount the destination HDD.
5. Copy all files/folders from VMFS6 to destination (Ext4) HDD
6. Check the md hashes on destination HDD and found lot of errors!
Almost all big xxxx-flat.vmdk files had bad md5 value!

This means.. read files within ESXi and with vmfs6-tools in Linux make different result! Without any sign. This cause data corruption/lost.

(Remarks: Finally, I solved the problem. I made a Linux based NFS server, and copied all files from running ESXi to the destionation Ext4 HDD, through NFS. Faster xfer than SSH. I checked the md5 hashes again in Linux, and with this method all files was good. )

**Comment by glandium** [comment]
You want to file this on https://github.com/weafon/vmfs6-tool, not here.
